servers:
  children:
    linux:
      hosts:
        agh:
          ansible_host: 192.168.56.12
          ansible_connection: ssh
          ansible_user: user
    windows:
      hosts:
        winsrv:
          ansible_host: 192.168.56.10
          ansible_connection: ssh
          ansible_user: Administrator
          ansible_shell_type: cmd